apiVersion: v1
kind: Service
metada:
  name: nodejs 
  namespace: application
  spec:
    type: LoadBalancer
    selector:
      app: application
    ports:
     - protocol: TCP
       ports: 3000
       targetport: 3000
    
