apiVersion: v1
kind: Service
metadata:
  name: nodejs 
  namespace: application
spec:
    type: LoadBalancer
    selector:
      app: jenkins
    ports:
     - protocol: TCP
       ports: 3000
       targetPort: 3000
    
